### PR TITLE
v0.1

### LINKED ISSUE #2: Suggestion: Use ESLOV Connector standard
The ESLOV connector is mounted on various Arduino boards and shields (such as the [MKR GPS Shield](https://store.arduino.cc/arduino-mkr-gps-shield)). You can think of it as the QWIIC of Arduino. Details to its pinout and connector type are available under the **Documentation** tab of the MKR GPS Shield product page. There's also a link to the connectors [datasheet](https://content.arduino.cc/assets/ESLOV_connector.pdf).

### PR DESCRIPTION
**Pull request by generationmake**
release initial version

### CODE REVIEW

**Comment by aentinger** [comment]
Looking good :+1:

**Comment by generationmake** [comment]
HI @aentinger 
I added an Arduino ESLOV connector as you suggested.
I connected the EN-pin to the digital pin (2) of the connector. Is this OK or do you have better suggestions?

**Comment by wuehr1999** [comment]
Hi @generationmake @aentinger 
I think this is a very good solution suitable for many purposes.
Nice work!

**Comment by aentinger** [comment]
>I connected the EN-pin to the digital pin (2) of the connector. Is this OK or do you have better suggestions?

This is fine by me. Unfortunately there are not endless pins available on the ESLOV connector and since the TMF8801 I2C address needs to be reconfigured at every startup it's better to use Pin 2 for ENABLE/GPIO0 for daisy-chaining multiple breakout boards as proposed by you [here](https://github.com/generationmake/TMF8801MKRShield/pull/1#issuecomment-731740904). This would require a second ESLOV connector though.

**Comment by generationmake** [comment]
Hi @aentinger 
if you want to connect multiple sensors you could use the ESLOV connector for the first sensor breakout board. All other boards are connected using the 0.1 inch headers. Then every enable pin is connected to the GPIO0 of the previous board.

**Comment by aentinger** [comment]
That makes sense to me. I just wish it would be a plug'n'play solution rather than requiring hand-soldering a couple of thin wires. Risk of breaking cables or cold solder spots as well as a different mechanical load of each cable increase with each individually soldered connection. Unfortunately I've got no good solution for that problem either.

**Comment by aentinger** [comment]
One way to achieve this would be to have on the incoming ESLOV connector Pin 2 wired to ENABLE and to wire Pin 2 of the outgoing ESLOV connector to GPIO0/1. What do you think?

**Comment by generationmake** [comment]
I added a second ESLOV connector and connected GPIO0 to it.

**Comment by generationmake** [comment]
test with prototype was successful.

**Pull request merged**
